# Generated by Django 2.2.1 on 2019-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_letter',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
